# Generated by Django 5.0.1 on 2024-02-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_alter_tours_price_of_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='total_people',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zayavka',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
